### Health
GET http://localhost:9876/health

### GET Request
GET http://localhost:9876/health
User-Agent: GoPost-CLI/1.0

### Expected status assertion
GET http://localhost:9876/health
X-Expected-Status: 200
